[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding.x = 0
padding.y = 0

# decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 14
