# based on iterm2 theme https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/themes/iterm2.omp.json

"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = false
version = 2
console_title_template = "{{ .Shell }} in {{ .Folder }}"

[transient_prompt]
background = "transparent"
foreground = "#FFD700"
template = "{{if .Root}}\u26a1 {{end}}\u276f "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "os"
  style = "powerline"
  background = "#003543"
  foreground = "#fff"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}}"

    [blocks.segments.properties]
    windows = "\uf179"

  [[blocks.segments]]
  type = "session"
  style = "powerline"
  background = "#003543"
  foreground = "#d2ff5e"
  powerline_symbol = "\ue0b0"
  template = "{{ .UserName }} "

  [[blocks.segments]]
  type = "path"
  style = "powerline"
  background = "#0087D8"
  foreground = "#003544"
  powerline_symbol = "\ue0b0"
  template = " \ue5ff {{ .Path }} "

    [blocks.segments.properties]
    folder_separator_icon = "/"
    style = "full"

  [[blocks.segments]]
  type = "git"
  style = "powerline"
  background = "#d2ff5e"
  foreground = "#193549"
  powerline_symbol = "\ue0b0"
  template = " {{ .HEAD }}{{ if .Staging.Changed }} \uf046 {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} \uf044 {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }} \ueb4b {{ .StashCount }}{{ end }} "

    background_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}",
      "{{ if gt .Ahead 0 }}#89d1dc{{ end }}",
      "{{ if gt .Behind 0 }}#f17c37{{ end }}"
    ]

    [blocks.segments.properties]
    fetch_stash_count = true
    fetch_status = true

[[blocks]]
type = "prompt"
alignment = "right"

  [[blocks.segments]]
  type = "status"
  style = "powerline"
  background = "#33DD2D"
  foreground = "#242424"
  powerline_symbol = "\ue0b2"
  invert_powerline = true
  template = " {{ if gt .Code 0 }}\u2717 {{ reason .Code }}{{ else }}\u2713{{ end }} "

    background_templates = [
      "{{ if gt .Code 0 }}#f1184c{{ end }}"
    ]

    [blocks.segments.properties]
    always_enabled = true

  [[blocks.segments]]
  type = "executiontime"
  style = "powerline"
  background = "#49404f"
  foreground = "#ffffff"
  powerline_symbol = "\ue0b2"
  invert_powerline = true
  template = " {{ .FormattedMs }} "

  [[blocks.segments]]
  type = "battery"
  style = "powerline"
  background = "#f36943"
  foreground = "#242424"
  powerline_symbol = "\ue0b2"
  invert_powerline = true
  template = " {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}\uf295 \ueb2d "

    background_templates = [
      "{{if eq \"Charging\" .State.String}}#33DD2D{{end}}",
      "{{if eq \"Discharging\" .State.String}}#FFCD58{{end}}",
      "{{if eq \"Full\" .State.String}}#0476d0{{end}}"
    ]

  [[blocks.segments]]
  type = "python"
  style = "powerline"
  background = "#0087D8"
  foreground = "#003544"
  powerline_symbol = "\ue0b2"
  invert_powerline = true
  template = " \ue235 {{ .Venv }} "

    [blocks.segments.properties]
    display_mode = "context"
    fetch_virtual_env = true

  [[blocks.segments]]
  type = "time"
  style = "powerline"
  background = "#003543"
  foreground = "#fff"
  invert_powerline = true
  template = "<#fff> \ue641 </>{{ .CurrentDate | date .Format }} "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "root"
  style = "plain"
  foreground = "#FFD700"
  template = " \u26a1 "

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#FFD700"
  template = "\u276f "
